DROP TABLE IF EXISTS JOKES;
DROP SEQUENCE IF EXISTS JOKES_ID_SEQ;
CREATE SEQUENCE JOKES_ID_SEQ
  START WITH 1;

CREATE TABLE JOKES
(
  ID INTEGER PRIMARY KEY DEFAULT NEXTVAL('JOKES_ID_SEQ'),
  JOKE_TEXT VARCHAR,
  RATING INTEGER DEFAULT 0
);